### ISSUE TITLE
Add SpringSecurity

### ISSUE THREAD

**Issue by ghaseminya** [adminfaces/admin-showcase#12]
Hi @rmpestano 
I add SpringSecurity to adminfaces and test it ok,
Can i add it to adminfaces org?

**Comment by rmpestano** [comment]
Hi @ghaseminya,

I think it would be nice to have a [Admin Starter](https://github.com/adminfaces/admin-starter) project version using Spring Security because it is the starter project which have authentication and is "protected" by a logon page. What do you think?

Also note that we already have a[ tomcat based version](https://github.com/adminfaces/admin-starter-tomcat) of starter project which may help on a Spring based project.

Thank you!

**Comment by ghaseminya** [comment]
Yes, its better way to add spring security,
So i fork it and make some changes and PR,

**Comment by ghaseminya** [comment]
Hi @rmpestano 
I add spring security needed things to project, but admin template session manager didn't permit to work correctly...
Is it true work to remove admin template from admin start project for adding spring security?

**Comment by rmpestano** [comment]
Hi @ghaseminya,

you can ignore it if you add another security layer. By default, AdminSession returns always true for isLoggerIn method.

Now if you are having troubles with CDI and Spring take a look [at this issue](https://github.com/adminfaces/admin-template/issues/13) where we are trying (I didn't look at it yet) to integratee this project with Spring Boot.
